JSAP_file = """
{
  "host":"localhost",
  "oauth":{
    "enable":false,
    "register":"https://localhost:8443/oauth/register",
    "tokenRequest":"https://localhost:8443/oauth/token"
  },
  "sparql11protocol":{
    "protocol":"http",
    "port":8050,
    "query":{
      "path":"/query",
      "method":"POST",
      "format":"JSON"
    },
    "update":{
      "path":"/update",
      "method":"POST",
      "format":"JSON"
    }
  },
  "sparql11seprotocol":{
    "protocol":"ws",
    "availableProtocols":{
      "ws":{
        "port":9050,
        "path":"/subscribe"
      },
      "wss":{
        "port":9443,
        "path":"/secure/subscribe"
      }
    }
  }
}
"""
